const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);const setText=(key,val)=>$$(`[data-bind="${key}"]`).forEach(e=>e.textContent=val);const cfg=window.WEDDING||{};
window.addEventListener('load',()=>{setTimeout(()=>{$('#loader').style.opacity='0';setTimeout(()=>$('#loader').remove(),650)},400);applyConfig();});
function applyConfig(){['bride','groom','date','dateLong','time','venue','address','dress','intro','story1Title','story1Text','story2Title','story2Text','inviteText','closing','brideFamily','groomFamily'].forEach(k=>cfg[k]!=null&&setText(k,cfg[k]));const audio=$('#music');audio.src=cfg.music||'assets/music.mp3';$('#mapBtn').href=cfg.mapUrl||'#';const pics=cfg.photos||{};$$('[data-image]').forEach(el=>{const key=el.dataset.image;if(pics[key]){el.style.backgroundImage=`url("${pics[key]}")`;el.classList.add('has-image')}});renderSchedule();renderQR();}
function renderSchedule(){const box=$('#scheduleList');box.innerHTML='';(cfg.schedule||[]).forEach(x=>{box.insertAdjacentHTML('beforeend',`<div class="event"><div class="event-time">${x.time}</div><div><h3>${x.title}</h3><p>${x.text}</p></div></div>`)});}
function renderQR(){const el=$('#qr');const url=encodeURIComponent(cfg.mapUrl||location.href);el.innerHTML='';const img=new Image();img.alt='Location QR code';img.width=210;img.height=210;img.src=`https://api.qrserver.com/v1/create-qr-code/?size=210x210&data=${url}`;img.onerror=()=>el.textContent='QR';el.appendChild(img);}
$('#openBtn').addEventListener('click',async()=>{const site=$('#site'),audio=$('#music');site.classList.remove('locked');site.style.display='block';$('#musicBtn').style.display='grid';try{await audio.play();$('#musicBtn').classList.add('playing')}catch(e){}setTimeout(()=>$('#cover').scrollIntoView({behavior:'smooth'}),80)});
$('#musicBtn').addEventListener('click',()=>{const a=$('#music');if(a.paused){a.play();$('#musicBtn').classList.add('playing')}else{a.pause();$('#musicBtn').classList.remove('playing')}});
function tick(){const target=new Date(cfg.dateISO||'2026-12-12T17:00:00+05:30').getTime(),diff=Math.max(0,target-Date.now());const vals=[Math.floor(diff/86400000),Math.floor(diff/3600000)%24,Math.floor(diff/60000)%60,Math.floor(diff/1000)%60];['days','hours','minutes','seconds'].forEach((id,i)=>$('#'+id).textContent=String(vals[i]).padStart(2,'0'));}tick();setInterval(tick,1000);
$('#calendarBtn').addEventListener('click',()=>{const start=new Date(cfg.dateISO||'2026-12-12T17:00:00+05:30');const end=new Date(start.getTime()+2*60*60*1000);const fmt=d=>d.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');const ics=['BEGIN:VCALENDAR','VERSION:2.0','BEGIN:VEVENT',`DTSTART:${fmt(start)}`,`DTEND:${fmt(end)}`,`SUMMARY:${cfg.bride||'Bride'} & ${cfg.groom||'Groom'} — Wedding`,`LOCATION:${cfg.venue||''}, ${cfg.address||''}`,'END:VEVENT','END:VCALENDAR'].join('\r\n');const blob=new Blob([ics],{type:'text/calendar'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='wedding.ics';a.click();URL.revokeObjectURL(a.href)});
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.animate([{opacity:0,transform:'translateY(28px)'},{opacity:1,transform:'translateY(0)'}],{duration:800,easing:'cubic-bezier(.2,.7,.2,1)',fill:'both'})}),{threshold:.12});$$('.story-copy,.section-inner,.rings,.finale-content').forEach(e=>observer.observe(e));
